### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca.org#30]
Currently, https://openfisca.org/ is not valid as there is not certificate added for https (due to the site running on github-pages).

A possible solution is to use a reverse proxy, as it is done with other sites already.

**Comment by MattiSG** [comment]
Can we have a clear idea of the dependencies that will be added just to add an S on a readonly informational website before proceeding please?  :)

From what I understand, that means all the traffic will have to go through a restricted access French governmental server.
Beyond the community impact (SPOF that no other stakeholder can work on) and the fact that it will be very hard to go back to HTTP if there is a problem (browsers become pretty aggressive with this now, even without HSTS), I'm not certain there is a good appreciation of the impact on page load speed from places that are not mainland France. GitHub provides a very efficient edge network we can rely on for free, forcing all traffic to go through Roubaix while aiming for international expansion doesn't sound like the best move to me. The impact on beta.gouv.fr in the Pacific region is very noticeable.

**Comment by maukoquiroga** [comment]
> Can we have a clear idea of the dependencies that will be added

That **would be added**, were this to be prioritised for sure.

Now I have only two ideas for now:

- A reverse proxy
- Github's beta SSL program

> just to add an S

I'd be grateful we keep a clean language, I'm not certain irony is constructive here 🙂

> From what I understand, that means all the traffic will have to go through a restricted access French governmental server.

Why? We have a reverse proxy server already.

> Beyond the community impact (SPOF that no other stakeholder can work on) 

There's a KeePassX pull request open to avoid account/access related SPOFs.

> And the fact that it will be very hard to go back to HTTP if there is a problem (browsers become pretty aggressive with this now, even without HSTS)

Care to elaborate ? That's definitely to take into account.

> I'm not certain there is a good appreciation of the impact on page load speed from places that are not mainland France. GitHub provides a very efficient edge network we can rely on for free, forcing all traffic to go through Roubaix while aiming for international expansion doesn't sound like the best move to me. The impact on beta.gouv.fr in the Pacific region is very noticeable.

Mmm... and that's only because of proxying in Roubaix ? Or SSL handshake also ? That's a fair point. However, I think we should reason on thresholds. I'll have to try with a ssh-tunnel to test that myself.

The major pro here is user experience, namely people increasingly blocking non-https traffic. Increase in SEO would be too marginal to count.

Cons include potential longer times due to handshaking and traffic routing. Though for a static site like OpenFisca's I don't know, need to test.

**Comment by MattiSG** [comment]
> Github's beta SSL program

I haven't been able to find a reference on that, do you have one? 🙂

> I'm not certain irony is constructive here

No irony was meant. I fail to see the user value in serving a purely informational website over an encrypted tunnel. I just see PR value, which is nice but that I boiled down to “adding an S”. Sorry if it felt offensive.

> Why? We have a reverse proxy server already.

Who is paying for it? 🤔 

> There's a KeePassX pull request

Ok, if there is a way for an authorised community maintainer to access the server that's much better. I did not know about that possibility. How can I learn more about it? 🙂

> Care to elaborate?

After having tested, that's actually the current behaviour of going to https://openfisca.org 😱

**I think the problem is really not about not serving HTTPS, but about serving it without being properly configured!** There should be a redirect to the HTTP version. Have a look at https://http.badssl.com for an example.

> people increasingly blocking non-https traffic

I haven't heard about that. That really doesn't sound practical. Do you mean end-users? Do you have any information on that? 🙂

For the time impact, I'll indeed let you test that antipodes latency + cache prevention have a larger impact than the initial TLS handshake.

**Comment by MattiSG** [comment]
I just applied the necessary DNS changes. This should propagate in about 3 hours, at which point we should be able to activate HTTPS support from the settings.

cc @guillett

**Comment by MattiSG** [comment]
This is now done. I switched on HTTPS support. You can access https://openfisca.org/. I will “enforce HTTPS” (redirect from HTTP to HTTPS) two days from now unless someone discovers a major problem with the HTTPS version.

Please make sure any (hot)link you provide to the HTTPS version works properly! If you do any testing, please report here 🙂 
cc @guillett @fpagnoux @Morendil @benjello

**Comment by MattiSG** [comment]
HTTPS enforcing is on!
